# Nixpacks configuration for Railway
# This file optimizes the build process for the Flask application

[phases.setup]
nixPkgs = ['python311', 'postgresql']

[phases.install]
cmds = [
    'pip install --upgrade pip',
    'pip install -r requirements.txt'
]

[phases.build]
cmds = [
    'python -c "import flask; print(f\"Flask version: {flask.__version__}\")"',
    'python -c "from app import app; print(\"App imported successfully\")"'
]

[start]
cmd = 'gunicorn wsgi:app --bind 0.0.0.0:$PORT --workers 4 --timeout 120'

[variables]
PYTHONUNBUFFERED = '1'
FLASK_ENV = 'production'