name: Deploy to Render

on:
  push:
    branches: [ master, main ]
  pull_request:
    branches: [ master, main ]

jobs:
  test:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v3
    
    - name: Set up Python 3.11
      uses: actions/setup-python@v3
      with:
        python-version: '3.11'
    
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
    
    - name: Test Flask app import
      run: |
        python -c "from app import app; print('Flask app imported successfully')"
    
    - name: Run basic tests
      run: |
        python -c "import models; print('Models imported successfully')"
        python -c "import config; print('Config imported successfully')"

  deploy:
    needs: test
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/master'
    
    steps:
    - name: Deploy to Render
      run: |
        echo "Deployment will be triggered automatically by Render"
        echo "Auto-deploy is enabled for master branch"